services:
  api01: &api
    image: rinha-de-backend:master
    hostname: api01
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8080
      - DB_POOL_SIZE=15
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rinha
      - SPRING_DATASOURCE_USERNAME=rinha
      - SPRING_DATASOURCE_PASSWORD=rinha
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "225MB"
  api02:
    <<: *api
    depends_on:
      - api01
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "90MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "10MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1